"""Delete useful order_id from Product

Revision ID: 219951375a43
Revises: ee6edaed6709
Create Date: 2026-02-18 18:18:11.962717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219951375a43'
down_revision: Union[str, Sequence[str], None] = 'ee6edaed6709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_order_id_fkey'), 'products', type_='foreignkey')
    op.drop_column('products', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('products_order_id_fkey'), 'products', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
