"""Initial

Revision ID: 7c9ba0533b82
Revises: 
Create Date: 2026-02-16 17:42:04.274847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9ba0533b82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_elements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_elements_name'), 'business_elements', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_user', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_seller', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_moderator', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password')
    )
    op.create_table('access_roles_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('read', sa.String(length=10), nullable=False),
    sa.Column('read_all', sa.String(length=10), nullable=False),
    sa.Column('create', sa.String(length=10), nullable=False),
    sa.Column('update', sa.String(length=10), nullable=False),
    sa.Column('update_all', sa.String(length=10), nullable=False),
    sa.Column('delete', sa.String(length=10), nullable=False),
    sa.Column('delete_all', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['business_elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'element_id', name='uq_access_rule_role_element')
    )
    op.create_index(op.f('ix_access_roles_rules_element_id'), 'access_roles_rules', ['element_id'], unique=False)
    op.create_index(op.f('ix_access_roles_rules_role_id'), 'access_roles_rules', ['role_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stars_amount', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('review_content', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('SMARTPHONES', 'LAPTOPS_AND_TABLETS', 'COMPUTERS_AND_COMPONENTS', 'TV_AND_VIDEO', 'AUDIO', 'PHOTO_AND_VIDEO_CAMERAS', 'GAMING', 'SMART_HOME', 'ACCESSORIES_ELECTRONICS', 'LARGE_APPLIANCES', 'SMALL_APPLIANCES', 'CLIMATE_CONTROL', 'KITCHEN_APPLIANCES', 'WOMENS_CLOTHING', 'MENS_CLOTHING', 'KIDS_CLOTHING', 'SHOES', 'BAGS_AND_WALLETS', 'ACCESSORIES', 'UNDERWEAR_AND_SLEEPWEAR', 'SPORT_CLOTHING', 'COSMETICS', 'PERFUMERY', 'HAIR_CARE', 'FACE_AND_BODY_CARE', 'MAKEUP', 'HEALTH_AND_PHARMACY', 'FURNITURE', 'HOME_TEXTILE', 'KITCHEN_AND_TABLEWARE', 'LIGHTING', 'DECOR_AND_INTERIOR', 'GARDEN_AND_PLANTS', 'REPAIR_AND_TOOLS', 'TOYS', 'BABY_CARE', 'CHILDREN_FURNITURE', 'SCHOOL_AND_CREATIVITY', 'SPORT_EQUIPMENT', 'FITNESS_AND_GYM', 'TOURISM_AND_CAMPING', 'BICYCLES_AND_SCOOTERS', 'AUTO_PARTS', 'CAR_ACCESSORIES', 'MOTORCYCLES_AND_SCOOTERS', 'TIRES_AND_WHEELS', 'FOOD_AND_DRINKS', 'PET_SUPPLIES', 'PET_FOOD', 'BOOKS', 'STATIONERY', 'BOARD_GAMES_AND_PUZZLES', 'HANDMADE_AND_HOBBY', 'COLLECTIBLES', 'JEWELRY', 'WATCHES', 'OTHER', name='productcategory'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_table('products')
    op.drop_table('reviews')
    op.drop_table('orders')
    op.drop_index(op.f('ix_access_roles_rules_role_id'), table_name='access_roles_rules')
    op.drop_index(op.f('ix_access_roles_rules_element_id'), table_name='access_roles_rules')
    op.drop_table('access_roles_rules')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_business_elements_name'), table_name='business_elements')
    op.drop_table('business_elements')
    # ### end Alembic commands ###
