"""Initial

Revision ID: a028d9b40dd2
Revises: 
Create Date: 2026-01-19 02:23:08.806350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a028d9b40dd2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password')
    )
    op.create_table('textreports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typicaldatas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_firstname', sa.String(), nullable=False),
    sa.Column('author_lastname', sa.String(), nullable=False),
    sa.Column('author_surname', sa.String(), nullable=False),
    sa.Column('group_number', sa.String(), nullable=False),
    sa.Column('record_book_number', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('work_title', sa.String(), nullable=False),
    sa.Column('instructor_firstname', sa.String(), nullable=False),
    sa.Column('instructor_lastname', sa.String(), nullable=False),
    sa.Column('instructor_surname', sa.String(), nullable=False),
    sa.Column('work_type', sa.Enum('THESIS_BACHELOR', 'THESIS_DIPLOMA', 'PROJECT_DIPLOMA', 'DISSERTATION_MASTER', 'COURSE_PROJECT', 'COURSE_WORK', 'PRACTICE_REPORT_EDUCATIONAL', 'PRACTICE_REPORT_PRODUCTION', 'PRACTICE_REPORT_SCIENTIFIC_PEDAGOGICAL', 'PRACTICE_REPORT', 'LAB_REPORT', 'PRACTICAL_WORK_REPORT', 'PROJECT_EXECUTION_REPORT', 'RESEARCH_REPORT_MASTER', 'REFERENCE', 'CALC_GRAPHIC_WORK', 'CALC_GRAPHIC_ASSIGNMENT', 'CALC_ASSIGNMENT', 'CONTROL_WORK', 'ESSAY', name='worktype'), nullable=False),
    sa.Column('completion_year', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('typicaldatas')
    op.drop_table('textreports')
    op.drop_table('users')
    # ### end Alembic commands ###
