"""Add oneToOne relation between review and product

Revision ID: f20053b6e2c9
Revises: 7c9ba0533b82
Create Date: 2026-02-16 18:18:27.428996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f20053b6e2c9'
down_revision: Union[str, Sequence[str], None] = '7c9ba0533b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'reviews', ['product_id'])
    op.create_foreign_key(None, 'reviews', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='unique')
    op.drop_column('reviews', 'product_id')
    # ### end Alembic commands ###
